server: 
  port: 8991 

spring: 
  application: 
    name: registration
  registrationdb: 
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: "jdbc:mysql://regdb-service:3306/REGISTRY?autoreconnect=true"
    username: "reg_user"
    password: "regUser1!"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000

eureka:
  client: 
    serviceUrl:
      defaultZone: "http://discovery-service:8761/eureka/"
  instance: 
    hostname: registration
    preferIpAddress: true

logging: 
  level: 
    root: INFO
    
---

spring: 
  profiles: test
  application: 
    name: registration  
  registrationdb: 
    driverClassName: org.h2.Driver
    jdbcUrl: "jdbc:h2:mem:registry"
    username: "reg_user"
    password: "regUser1!"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000